### ISSUE TITLE
Unsupported parameters for (community.general.gitlab_runner) module: group

### ISSUE THREAD

**Issue by btravouillon** [lgatellier/ansible-gitlab-runner-compose#5]
Release: 0.2.0
[community.general](https://galaxy.ansible.com/community/general): 6.2.0

The task **Ensure the runner is registered** fails with:
```
fatal: [docker01]: FAILED! => {"changed": false, "msg":
"Unsupported parameters for (community.general.gitlab_runner) module: group.
Supported parameters include: api_username, api_url, access_level, locked, maximum_timeout, 
run_untagged, state, owned, tag_list, description (name), api_password, api_token, project, 
registration_token, validate_certs, api_job_token, api_oauth_token, active."}
```

https://github.com/lgatellier/ansible-gitlab-runner-compose/blob/a7593544c7ecb7cf9fa3fa11bb420f5e2742177d/tasks/single-runner.yml#L25

Indeed, there is no `group` parameter in https://docs.ansible.com/ansible/latest/collections/community/general/gitlab_runner_module.html#ansible-collections-community-general-gitlab-runner-module

**Comment by lgatellier** [comment]
Hi @btravouillon, and thank you for your interest in this role !

To be honest, it is still a work in progress, since it relies on [a PR on `community.general`](https://github.com/ansible-collections/community.general/pull/3935) which has not been merged yet (but may soon be ?).

Let's keep this issue opened to track this point, I'll close it as soon as the other PR will be merged and `community.general` released :smile_cat:

**Comment by lgatellier** [comment]
@btravouillon [community.general 6.5.0](https://github.com/ansible-collections/community.general/releases/tag/6.5.0) has been released, including `group` parameter ! :smiley_cat:
